### ISSUE TITLE
Unresolved reference 'bot' 

### ISSUE THREAD

**Issue by HellFinger-s** [mail-ru-im/bot-python#6]
Hi, i istalled this library first by git clone and setup, but terminal wrote: no module named steptools. I install pip and go sudo apt install python-pip. There is no errors. So when i copypast code from official bot api webcite i get this error in pycharm: Unresolved reference 'bot' 
How can i solve this problem?

**Comment by majestic1488** [comment]
Hey.
I have the same problem

**Comment by dbf256** [comment]
When I try to run echo_bot after install of python library via pip I got

```
Traceback (most recent call last):
  File "C:/Projects/<...>/echo_bot.py", line 1, in <module>
    from bot.bot import Bot
  File "C:\Programs\Python27\lib\site-packages\bot\bot.py", line 16, in <module>
    from bot.dispatcher import Dispatcher, StopDispatching
ImportError: No module named dispatcher
```

**Comment by sergey-gladkow** [comment]
Hey, guys! Thanks for asking. I recommend you use a [virtual environment](https://docs.python.org/3/tutorial/venv.html). 
`python3 -m venv my_env_3 
source my_env_3/bin/activate 
pip install mailru-im-bot
` 
It'll help you manage package dependency conflicts.

**Comment by nightadmin** [comment]
Also you can install this library using ```
pip3 install mailru-im-bot
```
